version: '3'
services:
  cumulus:
    build: ./docker/cumulusCI
    container_name: sde-cumulus
    ports:
      - 8080:8080
    volumes:
      - /var/www/salesforce-demo-prod/:/root
    command: cci
    environment:
        - CUMULUSCI_KEY=2c5409bbc5ea321b # Must be 16
    network_mode: host
