# Because of `WORKDIR /root` in the image
# Or `- rsync -av --progress . /root --exclude .git` as a command.
workspace:
  base: /root
  path: /

pipeline:
  ci:
    image: guldmitry/cumulusci:0.1
    # Set that in the `Secrets` section of activated repository in agent.
    secrets: [ cumulusci_key ]
    commands:
      # No need to delete previous meta.
      - cci flow run ci_feature
    when:
      branch:
        exclude: master

  prod:
    image: guldmitry/cumulusci:0.1
    secrets: [ cumulusci_key ]
    commands:
      - cci flow run ci_master
      - cci flow run release_beta
    when:
      branch: master
